// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk1pmUXJWXFCs8IQFHkRb-Jrk9WBMfrBw',
    appId: '1:262225239570:web:138f41ae83f99d6d76c2cb',
    messagingSenderId: '262225239570',
    projectId: 'authentication-e106e',
    authDomain: 'authentication-e106e.firebaseapp.com',
    storageBucket: 'authentication-e106e.firebasestorage.app',
    measurementId: 'G-YG91929DER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy4njaj1TdTAQ6Itgyj_-mnZZs1yT2DXM',
    appId: '1:262225239570:android:cdb109b68deaf5e276c2cb',
    messagingSenderId: '262225239570',
    projectId: 'authentication-e106e',
    storageBucket: 'authentication-e106e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPlIy7QANueUjg1J1tsF6gffWhL-CNKig',
    appId: '1:262225239570:ios:2ea8c6d58021a11976c2cb',
    messagingSenderId: '262225239570',
    projectId: 'authentication-e106e',
    storageBucket: 'authentication-e106e.firebasestorage.app',
    androidClientId: '262225239570-nuascerf0kh29e4qmjtltrbkkmtu67le.apps.googleusercontent.com',
    iosClientId: '262225239570-ifjo93l9n7h28jo629nooqb4qmmf8sqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.relationAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPlIy7QANueUjg1J1tsF6gffWhL-CNKig',
    appId: '1:262225239570:ios:2ea8c6d58021a11976c2cb',
    messagingSenderId: '262225239570',
    projectId: 'authentication-e106e',
    storageBucket: 'authentication-e106e.firebasestorage.app',
    androidClientId: '262225239570-nuascerf0kh29e4qmjtltrbkkmtu67le.apps.googleusercontent.com',
    iosClientId: '262225239570-ifjo93l9n7h28jo629nooqb4qmmf8sqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.relationAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZfd8_LpxVg3YGyye19Pv0ice6djlFM9o',
    appId: '1:262225239570:web:db7691f7eb61d4ea76c2cb',
    messagingSenderId: '262225239570',
    projectId: 'authentication-e106e',
    authDomain: 'authentication-e106e.firebaseapp.com',
    storageBucket: 'authentication-e106e.firebasestorage.app',
    measurementId: 'G-CGNETMJXGJ',
  );
}
